
import java.util.ArrayList;

public class GUIFrame extends javax.swing.JFrame {

    BookingEntry bookingEntry = new BookingEntry();
    Waitlist waitlist = new Waitlist();
    Customer customer = new Customer();
    DBConnection connection = new DBConnection();
    Day day = new Day();
    Flight flight = new Flight();

    private void initialLoad() {        
        ArrayList<String> flights = flight.getFlights();
        flightComboBox.removeAllItems();
        flightComboBox2.removeAllItems();
        rFFlightComboBox.removeAllItems();
        for (String flightName : flights) {
            flightComboBox.addItem(flightName);
            flightComboBox2.addItem(flightName);
            rFFlightComboBox.addItem(flightName);
        }
        
        ArrayList<String> days = day.getDay();
        dateComboBox.removeAllItems();
        dateComboBox2.removeAllItems();
        for (String dates : days) {
            dateComboBox.addItem(dates);
            dateComboBox2.addItem(dates);
        }

        ArrayList<String> customers = customer.getCustomers();
        customerComboBox.removeAllItems();
        customerStatusComboBox.removeAllItems();
        rBCustomerComboBox.removeAllItems();
        rWCustomerComboBox.removeAllItems();
        for (String customerName : customers) {
            customerComboBox.addItem(customerName);
            customerStatusComboBox.addItem(customerName);
            rBCustomerComboBox.addItem(customerName);
            rWCustomerComboBox.addItem(customerName);
        }
        
        ArrayList<String> days2 = day.getCustomerBookingDays((String) rBCustomerComboBox.getSelectedItem());
        rBDateComboBox.removeAllItems();
        for (String rBDate : days2) {
            rBDateComboBox.addItem(rBDate);
        }
        
        ArrayList<String> flights2 = flight.getCustomerBookingFlights(
                (String) rBCustomerComboBox.getSelectedItem(), 
                (String) rBDateComboBox.getSelectedItem()
        );
        rBFlightComboBox.removeAllItems();
        for (String rBFlight : flights2) {
            rBFlightComboBox.addItem(rBFlight);
        }
        
        ArrayList<String> days3 = day.getCustomerWaitlistDays((String) rWCustomerComboBox.getSelectedItem());
        rWDateComboBox.removeAllItems();
        for (String rWDate : days3) {
            rWDateComboBox.addItem(rWDate);
        }
        
        ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                (String) rWCustomerComboBox.getSelectedItem(), 
                (String) rWDateComboBox.getSelectedItem()
        );
        rWFlightComboBox.removeAllItems();
        for (String rWFlight : flights3) {
            rWFlightComboBox.addItem(rWFlight);
        }
    }

    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addCustomerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customerTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        addCustomerTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        customerStatusComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerStatusTextArea = new javax.swing.JTextArea();
        viewCustomerStatusButton = new javax.swing.JButton();
        bookingPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        flightComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        addBookingButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        bookingStatusTextArea = new javax.swing.JTextArea();
        viewFlights = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dateComboBox2 = new javax.swing.JComboBox<>();
        viewFlightsButton = new javax.swing.JButton();
        viewWaitlistButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        flightComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        addFlightNameTextField = new javax.swing.JTextField();
        addFlightSeatsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addFlightButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        addDateTextField = new javax.swing.JTextField();
        addDateButton = new javax.swing.JButton();
        addDateStatusTextField = new javax.swing.JTextField();
        addFlightStatusTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rFFlightComboBox = new javax.swing.JComboBox<>();
        removeFlightButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rBCustomerComboBox = new javax.swing.JComboBox<>();
        rBFlightComboBox = new javax.swing.JComboBox<>();
        rBDateComboBox = new javax.swing.JComboBox<>();
        removeBookingButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        flightBookingTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rWCustomerComboBox = new javax.swing.JComboBox<>();
        rWDateComboBox = new javax.swing.JComboBox<>();
        rWFlightComboBox = new javax.swing.JComboBox<>();
        removeWaitlistButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        flightWaitlistTextArea = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setText("Flight Scheduler");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Name:");

        customerTextField.setColumns(15);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });

        addCustomerButton.setText("Add");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerTextField.setEditable(false);
        addCustomerTextField.setText("Names are CASE SENSITIVE");
        addCustomerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Customer name:");

        customerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusComboBoxActionPerformed(evt);
            }
        });

        customerStatusTextArea.setColumns(20);
        customerStatusTextArea.setRows(5);
        jScrollPane2.setViewportView(customerStatusTextArea);

        viewCustomerStatusButton.setText("View Status");
        viewCustomerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addContainerGap(144, Short.MAX_VALUE)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewCustomerStatusButton))
                                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                        .addComponent(customerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(106, 106, 106)))
                .addContainerGap())
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCustomerButton)
                        .addComponent(customerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(viewCustomerStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Add/View Customer", addCustomerPanel);

        jLabel2.setText("Flight:");

        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        flightComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                flightComboBoxItemStateChanged(evt);
            }
        });
        flightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Date:");

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer:");

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addBookingButton.setText("Add Booking");
        addBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingButtonActionPerformed(evt);
            }
        });

        bookingStatusTextArea.setColumns(20);
        bookingStatusTextArea.setRows(5);
        jScrollPane5.setViewportView(bookingStatusTextArea);

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))))
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(addBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Book Flight", bookingPanel);

        jLabel5.setText("Flight date:");

        dateComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        viewFlightsButton.setText("View Flights");
        viewFlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightsButtonActionPerformed(evt);
            }
        });

        viewWaitlistButton.setText("View Waitlist");
        viewWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWaitlistButtonActionPerformed(evt);
            }
        });

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        jScrollPane1.setViewportView(displayTextArea);

        jLabel6.setText("Flight number:");

        flightComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        flightComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewFlightsLayout = new javax.swing.GroupLayout(viewFlights);
        viewFlights.setLayout(viewFlightsLayout);
        viewFlightsLayout.setHorizontalGroup(
            viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewFlightsLayout.createSequentialGroup()
                        .addGap(0, 226, Short.MAX_VALUE)
                        .addGroup(viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewFlightsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewFlightsLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flightComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewFlightsButton)
                            .addComponent(viewWaitlistButton))
                        .addGap(226, 226, 226)))
                .addContainerGap())
        );
        viewFlightsLayout.setVerticalGroup(
            viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFlightsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(viewFlightsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewWaitlistButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Flight/Waitlist", viewFlights);

        addFlightNameTextField.setColumns(7);

        addFlightSeatsTextField.setColumns(7);
        addFlightSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightSeatsTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Flight name:");

        jLabel8.setText("Flight seats:");

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Date:");

        addDateTextField.setColumns(7);

        addDateButton.setText("Add Date");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        addDateStatusTextField.setEditable(false);
        addDateStatusTextField.setText("Date must be in format: YYYY-MM-DD");
        addDateStatusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateStatusTextFieldActionPerformed(evt);
            }
        });

        addFlightStatusTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addDateStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addFlightStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addFlightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addFlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFlightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFlightStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateButton)
                    .addComponent(addDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jTabbedPane1.addTab("Add Flight/Day", jPanel1);

        jLabel11.setText("Flight name:");

        rFFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeFlightButton.setText("Remove Flight");
        removeFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFlightButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Customer:");

        jLabel13.setText("Flight:");

        jLabel14.setText("Date:");

        rBCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rBCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBCustomerComboBoxActionPerformed(evt);
            }
        });

        rBFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rBDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rBDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBDateComboBoxActionPerformed(evt);
            }
        });

        removeBookingButton.setText("Remove Booking");
        removeBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookingButtonActionPerformed(evt);
            }
        });

        flightBookingTextArea.setColumns(20);
        flightBookingTextArea.setRows(5);
        jScrollPane3.setViewportView(flightBookingTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rFFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeFlightButton)
                    .addComponent(rFFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(2, 2, 2))
                    .addComponent(removeBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remove Flight/Booking", jPanel2);

        jLabel15.setText("Customer:");

        jLabel16.setText("Date:");

        jLabel17.setText("Flight:");

        rWCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rWCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rWCustomerComboBoxActionPerformed(evt);
            }
        });

        rWDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rWDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rWDateComboBoxActionPerformed(evt);
            }
        });

        rWFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeWaitlistButton.setText("Remove Waitlist Entry");
        removeWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWaitlistButtonActionPerformed(evt);
            }
        });

        flightWaitlistTextArea.setColumns(20);
        flightWaitlistTextArea.setRows(5);
        jScrollPane4.setViewportView(flightWaitlistTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rWFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rWCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rWDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeWaitlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rWCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(rWDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rWFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removeWaitlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remove Waitlist", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        initialLoad();
        bookingStatusTextArea.setText("");
        customerTextField.setText("");
        addCustomerTextField.setText("Names are CASE SENSITIVE");
        displayTextArea.setText("");
        customerStatusTextArea.setText("");
        flightBookingTextArea.setText("");
        addFlightNameTextField.setText("");
        addFlightSeatsTextField.setText("");
        addDateTextField.setText("");
        flightWaitlistTextArea.setText("");
        addFlightStatusTextField.setText("");
        addDateStatusTextField.setText("Date must be in format: YYYY-MM-DD");
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void addDateStatusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateStatusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDateStatusTextFieldActionPerformed

    private void addFlightSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightSeatsTextFieldActionPerformed

    private void flightComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboBox2ActionPerformed

    private void viewWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWaitlistButtonActionPerformed
        // TODO add your handling code here:
        displayTextArea.setText(waitlist.getWaitlist(
            (String) dateComboBox2.getSelectedItem())
        );
    }//GEN-LAST:event_viewWaitlistButtonActionPerformed

    private void viewFlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightsButtonActionPerformed
        // TODO add your handling code here:
        displayTextArea.setText(bookingEntry.getBookingEntry(
            (String) flightComboBox2.getSelectedItem(),
            (String) dateComboBox2.getSelectedItem())
        );
    }//GEN-LAST:event_viewFlightsButtonActionPerformed

    private void addBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingButtonActionPerformed
        String customer2 = customerComboBox.getSelectedItem().toString();
        String flight5 = flightComboBox.getSelectedItem().toString();
        String date = dateComboBox.getSelectedItem().toString();
        boolean isFilled = bookingEntry.checkIfBooked(customer2, flight5, date);
        boolean alreadyBooked;
        boolean alreadyOnWaitlist;
        boolean onList;

        if (isFilled == false) {
            alreadyBooked = bookingEntry.setBookingEntry(customer2, flight5, date);

            if (alreadyBooked == false) {
                ArrayList<String> customers = customer.getCustomers();
                rBCustomerComboBox.removeAllItems();
                rWCustomerComboBox.removeAllItems();
                for (String customerName : customers) {
                    rBCustomerComboBox.addItem(customerName);
                    rWCustomerComboBox.addItem(customerName);
                }
                
                ArrayList<String> days2 = day.getCustomerBookingDays((String) rBCustomerComboBox.getSelectedItem());
                rBDateComboBox.removeAllItems();
                for (String rBDate : days2) {
                    rBDateComboBox.addItem(rBDate);
                }
        
                ArrayList<String> flights2 = flight.getCustomerBookingFlights(
                        (String) rBCustomerComboBox.getSelectedItem(), 
                        (String) rBDateComboBox.getSelectedItem()
                );
                rBFlightComboBox.removeAllItems();
                for (String rBFlight : flights2) {
                    rBFlightComboBox.addItem(rBFlight);
                }
                
                ArrayList<String> days3 = day.getCustomerWaitlistDays((String) rWCustomerComboBox.getSelectedItem());
                rWDateComboBox.removeAllItems();
                for (String rWDate : days3) {
                    rWDateComboBox.addItem(rWDate);
                }
        
                ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                        (String) rWCustomerComboBox.getSelectedItem(), 
                        (String) rWDateComboBox.getSelectedItem()
                );
                rWFlightComboBox.removeAllItems();
                for (String rWFlight : flights3) {
                    rWFlightComboBox.addItem(rWFlight);
                }
                
                bookingStatusTextArea.setText("Sucessfully booked!");
            } else {
                bookingStatusTextArea.setText("Already booked this flight!");
            }
        } else {
            onList = bookingEntry.onBookingList(customer2);

            if (onList == false) {
                alreadyOnWaitlist = waitlist.addWaitlistEntry(customer2, flight5, date);

                if (alreadyOnWaitlist == false) {
                    bookingStatusTextArea.setText("No space left! Added to waitlist.");
                } else {
                    bookingStatusTextArea.setText("Already on waitlist!");
                }
            } else {
                bookingStatusTextArea.setText("Already booked this flight!");
            }
        }
    }//GEN-LAST:event_addBookingButtonActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboBoxActionPerformed

    private void flightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboBoxActionPerformed

    private void flightComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_flightComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboBoxItemStateChanged

    private void addCustomerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerTextFieldActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        boolean successful = customer.setCustomer(customerTextField.getText());

        if (successful == true) {
            ArrayList<String> customers = customer.getCustomers();
            customerComboBox.removeAllItems();
            customerStatusComboBox.removeAllItems();
            rBCustomerComboBox.removeAllItems();
            rWCustomerComboBox.removeAllItems();

            for (String customerName : customers) {
                customerComboBox.addItem(customerName);
                customerStatusComboBox.addItem(customerName);
                rBCustomerComboBox.addItem(customerName);
                rWCustomerComboBox.addItem(customerName);
            }
            addCustomerTextField.setText("Customer sucessfully added!");

        } else {
            addCustomerTextField.setText("Customer already exists!");
        }
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void customerStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerStatusComboBoxActionPerformed

    private void viewCustomerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerStatusButtonActionPerformed
        customerStatusTextArea.setText(customer.getCustomerStatus(
            (String) customerStatusComboBox.getSelectedItem())
        );
    }//GEN-LAST:event_viewCustomerStatusButtonActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        String date = addDateTextField.getText();
        if (date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            boolean successful = day.addDay(addDateTextField.getText());
            
            if(successful == true) {
                ArrayList<String> days = day.getDay();
                dateComboBox.removeAllItems();
                dateComboBox2.removeAllItems();
                for (String dates : days) {
                    dateComboBox.addItem(dates);
                    dateComboBox2.addItem(dates);
                }
                
                addDateStatusTextField.setText("Date added!");
            } else {
                addDateStatusTextField.setText("Date already exists!");
            }
        } else {
            addDateStatusTextField.setText("FORMAT MUST BE IN YYYY-MM-DD");
        }
    }//GEN-LAST:event_addDateButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
        String name = addFlightNameTextField.getText();
        int seats = 0;
        try {
            seats = Integer.parseInt(addFlightSeatsTextField.getText());
        } catch (NumberFormatException ex) {
            addFlightStatusTextField.setText("Seats must be an integer!");
            return;
        }
        
        boolean successful = flight.addFlight(name, seats);
        if (successful == true) {
            ArrayList<String> flights = flight.getFlights();
            flightComboBox.removeAllItems();
            flightComboBox2.removeAllItems();
            rFFlightComboBox.removeAllItems();
            for (String flightName : flights) {
                flightComboBox.addItem(flightName);
                flightComboBox2.addItem(flightName);
                rFFlightComboBox.addItem(flightName);
            }
            
            addFlightStatusTextField.setText("Flight added!");
        } else {
            addFlightStatusTextField.setText("Flight already exists!");
        }
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void removeBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookingButtonActionPerformed
        // TODO add your handling code here:
        String displayMessage = "";
        String customer = rBCustomerComboBox.getSelectedItem().toString();
        String flight4 = rBFlightComboBox.getSelectedItem().toString();
        String date = rBDateComboBox.getSelectedItem().toString();
        
        ArrayList<String> newCustomer = bookingEntry.removeBookingEntry(customer, flight4, date);
        
        ArrayList<String> days2 = day.getCustomerBookingDays((String) rBCustomerComboBox.getSelectedItem());
        rBDateComboBox.removeAllItems();
        for (String rBDate : days2) {
            rBDateComboBox.addItem(rBDate);
        }
        
        ArrayList<String> flights2 = flight.getCustomerBookingFlights(
                (String) rBCustomerComboBox.getSelectedItem(), 
                (String) rBDateComboBox.getSelectedItem()
        );
        rBFlightComboBox.removeAllItems();
        for (String rBFlight : flights2) {
            rBFlightComboBox.addItem(rBFlight);
        }
        
        ArrayList<String> days3 = day.getCustomerWaitlistDays((String) rWCustomerComboBox.getSelectedItem());
        rWDateComboBox.removeAllItems();
        for (String rWDate : days3) {
            rWDateComboBox.addItem(rWDate);
        }
        
        ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                (String) rWCustomerComboBox.getSelectedItem(), 
                (String) rWDateComboBox.getSelectedItem()
        );
        rWFlightComboBox.removeAllItems();
        for (String rWFlight : flights3) {
            rWFlightComboBox.addItem(rWFlight);
        }
        
        if (newCustomer.size() != 0) {
            String customer2 = newCustomer.get(0);
            String flight2 = newCustomer.get(1);
            String date2 = newCustomer.get(2);
        
            displayMessage = String.format("Booking successfully removed!" + "\n" +
                    "%s has been booked for flight %s on %s", customer2, flight2, date2);
        } else {
            displayMessage = "Booking successfully removed!";
        }

        flightBookingTextArea.setText(displayMessage);
    }//GEN-LAST:event_removeBookingButtonActionPerformed

    private void rBCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBCustomerComboBoxActionPerformed
        ArrayList<String> days2 = day.getCustomerBookingDays((String) rBCustomerComboBox.getSelectedItem());
        rBDateComboBox.removeAllItems();
        for (String rBDate : days2) {
            rBDateComboBox.addItem(rBDate);
        }
        
        ArrayList<String> flights2 = flight.getCustomerBookingFlights(
                (String) rBCustomerComboBox.getSelectedItem(), 
                (String) rBDateComboBox.getSelectedItem()
        );
        rBFlightComboBox.removeAllItems();
        for (String rBFlight : flights2) {
            rBFlightComboBox.addItem(rBFlight);
        }
    }//GEN-LAST:event_rBCustomerComboBoxActionPerformed

    private void rBDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBDateComboBoxActionPerformed
        // TODO add your handling code here:
        ArrayList<String> flights2 = flight.getCustomerBookingFlights(
                (String) rBCustomerComboBox.getSelectedItem(), 
                (String) rBDateComboBox.getSelectedItem()
        );
        rBFlightComboBox.removeAllItems();
        for (String rBFlight : flights2) {
            rBFlightComboBox.addItem(rBFlight);
        }
    }//GEN-LAST:event_rBDateComboBoxActionPerformed

    private void rWDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rWDateComboBoxActionPerformed
        // TODO add your handling code here:
        ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                (String) rWCustomerComboBox.getSelectedItem(), 
                (String) rWDateComboBox.getSelectedItem()
        );
        rWFlightComboBox.removeAllItems();
        for (String rWFlight : flights3) {
            rWFlightComboBox.addItem(rWFlight);
        }
    }//GEN-LAST:event_rWDateComboBoxActionPerformed

    private void rWCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rWCustomerComboBoxActionPerformed
        ArrayList<String> days3 = day.getCustomerWaitlistDays((String) rWCustomerComboBox.getSelectedItem());
        rWDateComboBox.removeAllItems();
        for (String rWDate : days3) {
            rWDateComboBox.addItem(rWDate);
        }
        
        ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                (String) rWCustomerComboBox.getSelectedItem(), 
                (String) rWDateComboBox.getSelectedItem()
        );
        rWFlightComboBox.removeAllItems();
        for (String rWFlight : flights3) {
            rWFlightComboBox.addItem(rWFlight);
        }
    }//GEN-LAST:event_rWCustomerComboBoxActionPerformed

    private void removeWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeWaitlistButtonActionPerformed
        String displayMessage = "";
        String customer = rWCustomerComboBox.getSelectedItem().toString();
        String flight2 = rWFlightComboBox.getSelectedItem().toString();
        String date = rWDateComboBox.getSelectedItem().toString();
        
        boolean successful = waitlist.removeWaitlistEntry(customer, flight2, date);
        
        ArrayList<String> days3 = day.getCustomerWaitlistDays((String) rWCustomerComboBox.getSelectedItem());
        rWDateComboBox.removeAllItems();
        for (String rWDate : days3) {
            rWDateComboBox.addItem(rWDate);
        }
        
        ArrayList<String> flights3 = flight.getCustomerWaitlistFlights(
                (String) rWCustomerComboBox.getSelectedItem(), 
                (String) rWDateComboBox.getSelectedItem()
        );
        rWFlightComboBox.removeAllItems();
        for (String rWFlight : flights3) {
            rWFlightComboBox.addItem(rWFlight);
        }
        
        if (successful == true) {
            displayMessage = "Waitlist entry succesfully removed!";
        } else {
            displayMessage = "Something went wrong!";
        }
        
        flightWaitlistTextArea.setText(displayMessage);
    }//GEN-LAST:event_removeWaitlistButtonActionPerformed

    private void removeFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFlightButtonActionPerformed
        // TODO add your handling code here:
        String result = flight.removeFlight((String) rFFlightComboBox.getSelectedItem());
        flightBookingTextArea.setText(result);
        
        ArrayList<String> customers = customer.getCustomers();
        rBCustomerComboBox.removeAllItems();
        rWCustomerComboBox.removeAllItems();
        for (String customerName : customers) {
            rBCustomerComboBox.addItem(customerName);
            rWCustomerComboBox.addItem(customerName);
        }
        
        ArrayList<String> flights = flight.getFlights();
        flightComboBox.removeAllItems();
        flightComboBox2.removeAllItems();
        rFFlightComboBox.removeAllItems();
        for (String flightName : flights) {
            flightComboBox.addItem(flightName);
            flightComboBox2.addItem(flightName);
            rFFlightComboBox.addItem(flightName);
        }
    }//GEN-LAST:event_removeFlightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        GUIFrame guiFrame = new GUIFrame();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                guiFrame.setVisible(true);
                guiFrame.initialLoad();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookingButton;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JTextField addCustomerTextField;
    private javax.swing.JButton addDateButton;
    private javax.swing.JTextField addDateStatusTextField;
    private javax.swing.JTextField addDateTextField;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JTextField addFlightNameTextField;
    private javax.swing.JTextField addFlightSeatsTextField;
    private javax.swing.JTextField addFlightStatusTextField;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JTextArea bookingStatusTextArea;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JComboBox<String> customerStatusComboBox;
    private javax.swing.JTextArea customerStatusTextArea;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JComboBox<String> dateComboBox2;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JTextArea flightBookingTextArea;
    private javax.swing.JComboBox<String> flightComboBox;
    private javax.swing.JComboBox<String> flightComboBox2;
    private javax.swing.JTextArea flightWaitlistTextArea;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> rBCustomerComboBox;
    private javax.swing.JComboBox<String> rBDateComboBox;
    private javax.swing.JComboBox<String> rBFlightComboBox;
    private javax.swing.JComboBox<String> rFFlightComboBox;
    private javax.swing.JComboBox<String> rWCustomerComboBox;
    private javax.swing.JComboBox<String> rWDateComboBox;
    private javax.swing.JComboBox<String> rWFlightComboBox;
    private javax.swing.JButton removeBookingButton;
    private javax.swing.JButton removeFlightButton;
    private javax.swing.JButton removeWaitlistButton;
    private javax.swing.JLabel title;
    private javax.swing.JButton viewCustomerStatusButton;
    private javax.swing.JPanel viewFlights;
    private javax.swing.JButton viewFlightsButton;
    private javax.swing.JButton viewWaitlistButton;
    // End of variables declaration//GEN-END:variables
}
